#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_COURSE[0]}") && pwd)

# General tools
sudo dnf install bat g++ neovim npm ripgrep zsh kitty-terminfo

# Postgres
sudo dnf install postqresql postgresql-server postgresql-contrib postgresql-docs postgresql-test postgresql-jdbc postgresql-odbc

# Elixir
sudo dnf install inotify tools

sudo postgresql-setup --initdb --unit postgresql
systemctl enable postgresql
systemctl start postgresql


# Symlinking configs
rm -rf $HOME/.config/libinput-gestures.conf
ln -s $DOTFILES/libinput-gestures.conf $HOME/.config/libinput-gestures.conf

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.zshrc
ln -s $DOTFILES/zsh/zshrc $HOME/.zshrc

rm -rf $HOME/.config/lf
ln -s $DOTFILES/lf $HOME/.config/lf

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.local/bin
rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# Install and symlink Kitty (assuming ~/.local/bin is in
# your system-wide PATH)
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
ln -sf ~/.local/kitty.app/bin/kitty ~/.local/kitty.app/bin/kitten ~/.local/bin/
# Place the kitty.desktop file somewhere it can be found by the OS
cp ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications/
# If you want to open text files and images in kitty via your file manager also add the kitty-open.desktop file
# cp ~/.local/kitty.app/share/applications/kitty-open.desktop ~/.local/share/applications/
# Update the paths to the kitty and its icon in the kitty.desktop file(s)
sed -i "s|Icon=kitty|Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty*.desktop
sed -i "s|Exec=kitty|Exec=/home/$USER/.local/kitty.app/bin/kitty|g" ~/.local/share/applications/kitty*.desktop

# rm -rf $HOME/.config/nvim/init.lua
# ln -s $DOTFILES/nvim/init.lua $HOME/.config/nvim/init.lua

# mkdir -p $HOME/.config/nvim/lua/user
# rm -rf $HOME/.config/nvim/lua/user/plugins.lua
# rm -rf $HOME/.config/nvim/lua/user/options.lua
# rm -rf $HOME/.config/nvim/lua/user/keymaps.lua
# ln -s $DOTFILES/nvim/lua/user/plugins.lua $HOME/.config/nvim/lua/user/plugins.lua
# ln -s $DOTFILES/nvim/lua/user/options.lua $HOME/.config/nvim/lua/user/options.lua
# ln -s $DOTFILES/nvim/lua/user/keymaps.lua $HOME/.config/nvim/lua/user/keymaps.lua

# rm -rf $HOME/.config/helix
# ln -s $DOTFILES/helix $HOME/.config/helix

# # Language servers
# if ! command -v typescript-language-server &> /dev/null; then
#   sudo npm install --global typescript typescript-language-server
# fi
