#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_COURSE[0]}") && pwd)

sudo dnf install bat g++ kitty neovim npm ripgrep zsh

rm -rf $HOME/.config/libinput-gestures.conf
ln -s $DOTFILES/libinput-gestures.conf $HOME/.config/libinput-gestures.conf

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.zshrc
ln -s $DOTFILES/zsh/zshrc $HOME/.zshrc

rm -rf $HOME/.config/lf
ln -s $DOTFILES/lf $HOME/.config/lf

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.local/bin
rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

# rm -rf $HOME/.config/nvim/init.lua
# ln -s $DOTFILES/nvim/init.lua $HOME/.config/nvim/init.lua

# mkdir -p $HOME/.config/nvim/lua/user
# rm -rf $HOME/.config/nvim/lua/user/plugins.lua
# rm -rf $HOME/.config/nvim/lua/user/options.lua
# rm -rf $HOME/.config/nvim/lua/user/keymaps.lua
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim
# ln -s $DOTFILES/nvim/lua/user/plugins.lua $HOME/.config/nvim/lua/user/plugins.lua
# ln -s $DOTFILES/nvim/lua/user/options.lua $HOME/.config/nvim/lua/user/options.lua
# ln -s $DOTFILES/nvim/lua/user/keymaps.lua $HOME/.config/nvim/lua/user/keymaps.lua


# rm -rf $HOME/.config/helix
# ln -s $DOTFILES/helix $HOME/.config/helix

# # Language servers
# if ! command -v typescript-language-server &> /dev/null; then
#   sudo npm install --global typescript typescript-language-server
# fi
