theme = "mytheme"

[editor]
# cursorline = true
color-modes = true
line-number = "relative"
mouse = true
bufferline = "always"
end-of-line-diagnostics = "hint"
scrolloff = 0

[editor.inline-diagnostics]
# cursor-line = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1
    
[editor.lsp]
display-messages = true

[editor.statusline]

# mode.normal = "NORMAL"
# mode.insert = "INSERT"
# mode.select = "SELECT"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"


[keys.normal.L]
t = "@|stag<ret>sxxx<ret>c"

[keys.normal]
ret = "goto_word"
A-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',

# Allows selection of multiple files
  # ':sh rm -f /tmp/files2open',
  # ':set mouse false',
  # ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/files2open',
  # ':redraw',
  # ':set mouse true',
  # ':open /tmp/files2open',
  # 'select_all',
  # 'split_selection_on_newline',
  # 'goto_file',
  # ':buffer-close! /tmp/files2open',
]
A-g = [
    # ":write-all",
    ":new",
    ":insert-output lazygit",
    ":set mouse false", # First disable mouse to hint helix into activating it
    ":set mouse true",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]
esc = ["collapse_selection", "keep_primary_selection"]
# ";" = "command_mode"
X = "extend_line_above"
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"


# Line swaps
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

C-n = ["move_line_down", "scroll_down"]
C-p = ["move_line_up", "scroll_up"]
C-d = ["align_view_top", "half_page_down", "align_view_center", "goto_line_start"]
C-u = ["align_view_bottom", "half_page_up", "align_view_center", "goto_line_start"]

[keys.normal.space]
u = ":update"
q = ":buffer-close"
# remap repeat_last_motion from alt+s
# map C-a to increment??
# remap A-( and A-) for rotate_selection_contents and A-, for remove primary selection
# remap A-` (make uppercase)
# A-; (flip macos_option_as_alt yesselection)
#
#


[keys.select]
A-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
A-g = [
    # ":write-all",
    ":new",
    ":insert-output lazygit",
    ":set mouse false", # First disable mouse to hint helix into activating it
    ":set mouse true",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]
# esc = ["collapse_selection", "keep_primary_selection"]
# ";" = "command_mode"
X = "extend_line_above"
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"

# Line swaps
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
