theme = "nord"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false


[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
display-messages = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[keys.normal]
        esc = ["collapse_selection", "keep_primary_selection"]
";" = "command_mode"
X = "extend_line_above"
C-z = "increment"
C-n = ["move_line_down", "scroll_down"]
C-p = ["move_line_up", "scroll_up"]
C-d = ["align_view_top", "half_page_down", "align_view_center", "goto_line_start"]
C-u = ["align_view_bottom", "half_page_up", "align_view_center", "goto_line_start"]

[keys.normal.space]
u = ":update"
q = ":buffer-close"
# remap repeat_last_motion from alt+s
# map C-a to increment??
# remap A-( and A-) for rotate_selection_contents and A-, for remove primary selection
# remap A-` (make uppercase)
# A-; (flip macos_option_as_alt yesselection)
