alias v="nvim"

autoload -U colors && colors

export PROMPT="%B%{$fg[blue]%}%~%b %{$reset_color%}"
# export PROMPT="%d{red}"

export EDITOR=nvim

export CC=gcc

path=(
	/home/linuxbrew/.linuxbrew/opt/postgresql@16/bin
	/bin
	/usr/bin
	/usr/local/bin
	$HOME/bin
	$HOME/.cargo/bin
	$HOME/.local/bin
	$HOME/.config/composer/vendor/bin
	./vendor/bin
	$HOME/.emacs.d/bin
	$HOME/Repositories/dotfiles/scripts
	$path
)
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# pnpm
export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export GOPATH=$HOME/go

# Erlang
export ERL_AFLAGS="-kernel shell_history enabled"
