alias v="nvim"
alias h="hx"

autoload -U colors && colors

export PROMPT="%B%{$fg[blue]%}%~%b %{$reset_color%}"
# export PROMPT="%d{red}"

export EDITOR=nvim

export CC=gcc-12

path=(
	/bin
	/usr/bin
	/usr/local/bin
	$HOME/.local/bin
	$HOME/.config/composer/vendor/bin
	./vendor/bin
	$HOME/.emacs.d/bin
	$path
)
